version: '3'

services:
  db:
    image: mysql:5.7
    container_name: mysql-db
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wordpress-network
    restart: always
    env_file: .env

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wordpress
    volumes:
      - ./wordpress:/var/www/html
    ports:
      - "8088:80"
    networks:
      - wordpress-network
    restart: always
    env_file: .env

volumes:
  db_data:

networks:
  wordpress-network: